### ISSUE TITLE
SetUp KanBan board

### ISSUE THREAD

**Issue by lojacho** [lojacho/Recipe-app#11]
This is the link to our [board]( https://github.com/dgcuenca/Recipe-app/projects/1)
And we are two students in this group.

**Comment by Davidosky007** [comment]
Hi @dgcuenca @belaymit 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* All links to the board are working 👍 
* Well-written issue description 👍 

## Required Changes ♻️
* Kindly add descriptions to the tasks 
![image](https://user-images.githubusercontent.com/52497246/232552529-f88b88a7-5c51-407a-8c76-536170a9202e.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lojacho** [comment]
Hello @Davidosky007 requirements were implemented.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @dgcuenca and @belaymit,

✔️ Descriptive tasks

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
